[project]
name = "study-githubactions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "flask>=3.1.1",
    "mypy>=1.16.1",
    "ruff>=0.12.0",
]
