# auth-test.yaml
name: Auth test
run-name: Auth test by @${{ github.actor }}

on:
  workflow_dispatch: # Manually run

permissions:
  contents: read
  id-token: write

jobs:
  auth_test:
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      id-token: write # This is required for requesting the OIDC JWT Token
    environment:
      name: TEST
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ vars.PROJECT_ID }}
        workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/test-mizuki-oidc/providers/github-actions
        service_account: mizuki-test-github-actions@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use Cloud SDK
      run: gcloud config list