name: CICD

on:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11']
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
          - name: Install uv
            uses: astral-sh/setup-uv@v4
          - name: Install dependencies
            run: uv sync
          - name: Format with black
            if: always()
            run: uv run black --check --config=pyproject.toml .
          - name: Lint with ruff
            if: always()
            run: uv run ruff check --config=pyproject.toml .
          - name: Type check with mypy
            if: always()
            run: uv run mypy --config-file=pyproject.toml .
          - name: Build Docker image
            run: make build
          - name: Push Docker image
            run: make push
            