name: Manual

on:
  workflow_dispatch:
    inputs:
        greeting:
            type: string
            default: "Hello, world!"
            required: true
            description: "The greeting to use"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "{{ inputs.greeting }}"
      - uses: actions/checkout@v4